PostHog/posthog-cloud

multi_tenancy/templates/signup.html
Made a small tweak to the hosted page to keep the user intention focused. Added some copy to encourage users to go through with signup because the "trial" still provides you all functionality. 
I didn't do much to beautify the page because I think that will become part of the [overhaul](https://github.com/PostHog/posthog.com/issues/129)
=> Focus hosted sign up page

multi_tenancy/urls.py
Overwrites `posthog-production`-only URL patterns using [route precedence](https://docs.djangoproject.com/en/3.1/topics/http/urls/#how-django-processes-a-request) instead of overriding with hard-coded indexes.
=> Fix: URL patterns

multi_tenancy_settings.py
Previously we were using the oss "login.html" page which meant there was no way of getting from the login page to the signup page.
=> change template order

.github/workflows/ci-backend.yml, multi_tenancy/tests/test_billing.py, multi_tenancy/tests/test_signup.py
This makes PostHog Cloud compatible with PostHog/posthog#1562.
NB: CI will be failing here, because it runs against main repo `master`, while I'm adjusting this branch against `teams`.
=> Update Cloud for posthog#1562 going live

app.json
Previously `app.json` was configured to use a fork of the Heroku Python buildpack, rather than the official buildpack. Using the official buildpack is recommended, since:
1. The fork is using the old S3 bucket, so doesn't have newer versions of Python/Heroku-20 support
2. The official buildpacks have strict access controls and auditing, compared to third party buildpacks
3. The Heroku build workers pre-cache the official buildpacks, saving the need to Git clone the repo
This is the `posthog-production` equivalent of PostHog/posthog/pull/2151.
=> Switch to the official Heroku Python buildpack

.github/workflows/ci-backend.yml, .gitignore, multi_tenancy/models.py, multi_tenancy/tests/test_billing.py
- Adds logic for this repo to handle billing logic that's applicable only to cloud (i.e. previously the `ee` app on the main repo would decide which features each plan had enabled, with this PR, the logic can go on this repo).
- Will validate that plans are active before enabling paid features.
=> Improvements to billing logic

multi_tenancy/tests/test_signup.py, multi_tenancy/urls.py
Some tests that were missed in the organization signup refactor.﻿ This PR also fix the `api/signup` override from posthog-production that allows signing up to a specific plan.
=> Fix tests from #2709

multi_tenancy/serializers.py, multi_tenancy/tests/test_billing.py
Adds the referenced attribute to enable customization for metered-based billing plans in the front-end.
=> Add `is_metered_billing` attribute to plan serializer

messaging/mail.py, multi_tenancy/tests/test_signup.py
- Fixes cloud tests from https://github.com/PostHog/posthog/pull/2937.
- Adds `Reply-To` header to emails (per https://github.com/PostHog/posthog/pull/2846).﻿
=> Fixes tests for 2937 (posthog) & add Reply-To header in emails

multi_tenancy/tests/test_billing.py, multi_tenancy/views.py
Fixes https://sentry.io/organizations/posthog/issues/2180207809/?project=1899813 where if a user had no organization, the app would crash as the `/api/user/` endpoint would fail.﻿
=> Fix user not having organization edge case

package.json
Running `yarn build` in `deploy` fails with:
```
$ echo "Building Webpack" && NODE_ENV=production webpack --config webpack.config.js && cp -a frontend/public/* frontend/dist/ && npm run copy-scripts
/bin/sh: 1:        Building Webpack
webpack: not found
```
Probably NODE_ENV is set to `production` somewhere and thus it doesn't install dev deps. This [should fix it](https://classic.yarnpkg.com/en/docs/cli/install/#toc-yarn-install-production-true-false).
=> Install dev deps

multi_tenancy/serializers.py, multi_tenancy/tests/test_signup.py
Currently users would see no error since we removed the generic error
toast.
Sentry error: https://sentry.io/organizations/posthog/issues/1892659475/?project=1899813&query=is%3Aunassigned+is%3Aunresolved
=> Signup validation: validate email does not exist

multi_tenancy/tests/test_billing.py, multi_tenancy/urls.py
- Plans endpoints are now `/api/plans...`. The problem with having them on the root endpoint is that when on self-hosted, if you requested `/plans`, the request would return a 200 (because it would be routed to the front-end), when we actually need a 404 error response (otherwise this leads to a leak in a Kea reducer).
=> Move plans endpoints under /api

multi_tenancy/models.py, multi_tenancy/serializers.py, multi_tenancy/tests/test_billing.py, multi_tenancy/views.py
Subsequent PR to https://github.com/PostHog/posthog/pull/3360.
- Remove server-side formatting of billing numbers.
- Remove legacy `allowance` property of `Plan` model.
=> Remove billing server-side formatting

.github/workflows/ci-backend.yml
https://github.com/PostHog/posthog/pull/3417 switched the way we run tests to use `pytest`. Particularly, this switch changed the way we set up the CH DB which was causing our local tests to fail because the CH was not set up. This PR fixes that and moves this repo to use pytest too in the CI.
For future reference, it's important to remember to update this PR too when changing the way we run tests in the main repo.
=> Fix CI & move to pytest

multi_tenancy/stripe.py, multi_tenancy/tests/cassettes/test_billing_period_special_handling_for_startup_plan, multi_tenancy/tests/test_webhooks.py, multi_tenancy/views.py, requirements.txt
Everytime a new card is added for future usage (`mode = setup`), we automatically set that card as the default payment method for subscriptions on Stripe.
Previously this was causing a billing issue in which customers in usage-based pricing plans weren't billed after their initial period and/or trial elapsed because Stripe didn't have any "default" payment method on file. More context on [this thread](https://posthog.slack.com/archives/C01P3BQ1LFL/p1614689260000500)
This PR also upgrades Stripe library to the latest version.
=> Set default payment method on Stripe after card registration

messaging/tasks.py
Temporarily disables the event ingestion reminder email due to some reports from users of the email being sent when it shouldn't have been. We're also transitioning these emails to use the core repo resources.
=> Temporarily disable event ingestion reminder email

multi_tenancy/middleware.py
Fixes error preventing Cloud from working for users if their current project has a non-Latin-1-compatible character.
Reported by a user on Slack.
=> Make sure ph_current_project_name is latin-1-safe

.github/workflows/ci-backend.yml, multi_tenancy/tests/test_signup.py
- PR stops expecting a specific error response when an account is being created with a duplicate email as this message can change in the main repo.
- PR also adds missing dependency for tests on `pytest_mock` that was introduced in https://github.com/PostHog/posthog/pull/3705
Friendly reminder if we introduce new test dependencies in the main repo to update posthog-cloud too.
=> Fix signup tests

multi_tenancy/models.py, multi_tenancy/tests/test_billing.py
This PR matches premium features for EE `enterprise` plan to all paid plans on cloud (except legacy Starter) so we don't have to update posthog-cloud every time this list changes. We might change this behavior in the future if plans diverge, but for now we're matching all features.
=> Match EE premium features on Cloud

multi_tenancy/serializers.py, multi_tenancy/tests/test_billing.py, multi_tenancy/tests/test_signup.py, multi_tenancy/urls.py, multi_tenancy/views.py
**Builds on** https://github.com/PostHog/posthog/pull/3855. Please review the original PR for full context and motivation, but mainly we keep on our quest to reduce the time it requires for the app to be rendered.
- This PR removes the cloud overriding of `/api/user/` in favor of an `/api/billing/` endpoint.
- The `/api/billing` endpoint that is introduced incorporates the same information we previously had under the `"billing"` key in the `/api/user` response. Now through a DRF serializer too.
- No logic changes are introduced.
=> User V2 Cloud Refactor

multi_tenancy/serializers.py, multi_tenancy/stripe.py, multi_tenancy/tests/cassettes/test_can_get_bill_usage_for_current_period, multi_tenancy/tests/cassettes/test_failed_request_to_stripe_fails_gracefully, multi_tenancy/tests/test_billing.py
From user's feedback in the last billing period and @fuziontech's inspiration, we will now show the bill (in $) for your current running period to avoid any surprises.
- This PR introduces the backend changes required for this. Fetching the relevant information from Stripe to show it to the user.﻿
=> Report current $ bill usage

.gitignore, multi_tenancy/migrations/0005_organizationbilling.py
`multitenancy.OrganizationBilling` does not inherit from `posthog.Organization` and is only related to it via a OneToOne primary key field, but for some reason the former model was based on the latter in the migration. This has not posed a problem until now, but after upgrading Django to 3.1 in https://github.com/PostHog/posthog/pull/4007 apparently causes migrations to now add a new field `organization_ptr_id`, which the Python model does not actually work with.
=> Don't base OrganizationBilling on Organization

multi_tenancy/stripe.py, multi_tenancy/tasks.py, multi_tenancy/tests/test_tasks.py
Updates billing code to use take in `subscription_ids` and retrieve the items from those, instead of off of the org billing model.
=> Use subscription id to report billing
