PostHog/posthog-cloud

multi_tenancy/templates/signup.html
This is a supplement to PR PostHog/posthog#1204.
=> Fix password validation and improve minimums notice (issue PostHog/posthog#1197)

.gitignore, README.md, dev.Dockerfile, docker-compose.dev.yml
I tried to base (using `FROM`) this build off the posthog:latest docker image but building is still required so there is some duplication of configs between the Dockerfiles here and on proper posthog repo.
=> Setup posthog-production to run on docker-compose for dev

Procfile
This will automatically migrate our clickhouse migrations on release
=> Migrate clickhouse on release

messaging/tasks.py, messaging/tests/test_messaging.py
Related Sentry bug: https://sentry.io/organizations/posthog/issues/1912380295/
=> Small optimizations for follow-up email sending

prod.web.Dockerfile, prod.worker.Dockerfile
=> Fix cmd's for dockerfiles

multi_tenancy/admin.py, multi_tenancy/models.py
Make it easier to find the right organization based on name or email
=> Add search to billing

.env.template, bin/develop, multi_tenancy/tests/test_billing.py, multi_tenancy/utils.py, multi_tenancy/views.py
If clickhouse is down for whatever reason api/user will fail too.
=> Catch issues with clickhouse in api/user

multi_tenancy/serializers.py, multi_tenancy/views.py
Complements https://github.com/PostHog/posthog/pull/2709, which must be merged first. After merging, tests must be run again to make sure this PR is working as expected.
=> [Pair PR] - Refactor /api/signup to Organization

prod.web.Dockerfile
This also fixes the issue with building the kafka dependencies needed for ECS in production
=> Clean up building of plugins for prod

prod.web.Dockerfile
Makes JS errors in sentry useful
=> Do not remove source maps from production dockerfile

multi_tenancy/tests/test_signup.py
Broken by https://github.com/PostHog/posthog/pull/3103
=> Fix signup tests

multi_tenancy/models.py
=> Enable premium features for standard plan

package.json
Hopefully fixes errors like these:
=> Switch from npm to yarn to have deterministic builds with yarn.lock

multi_tenancy_settings.py
Will resolve https://sentry.io/organizations/posthog/issues/2213131486. And also an outage.
=> Cast BILLING_* env var values to ints

multi_tenancy/tests/test_login.py
- Test login works
- Test login works without team
=> Add login tests

multi_tenancy/models.py, multi_tenancy/tasks.py, multi_tenancy/tests/test_webhooks.py, multi_tenancy/views.py
Adds `billing subscription activated`, `billing subscription paid` & `billing card validated` events to be reported to PostHog.﻿
=> Report billing events

multi_tenancy/admin.py
- Allows searching OrganizationBilling objects in the admin using Stripe IDs.
- Allows editing checkout session in the admin interface.
=> Search by Stripe attributes (admin)

multi_tenancy/templates/login.html
May be the solution to PostHog/posthog#3415.
=> Fix login redirect

multi_tenancy/urls.py
Fixes `login_required` reference in preparation for https://github.com/PostHog/posthog/pull/3701/
=> Fix login_required reference

.github/workflows/ci-backend.yml, messaging/tests/test_messaging.py, multi_tenancy/tests/base.py, multi_tenancy/tests/test_billing.py, multi_tenancy/tests/test_login.py, multi_tenancy/tests/test_middleware.py, multi_tenancy/tests/test_signup.py, multi_tenancy/tests/test_tasks.py, multi_tenancy/tests/test_utils.py, multi_tenancy/tests/test_webhooks.py
Refactors this repo's tests to follow with https://github.com/PostHog/posthog/pull/3774 changes.
=> Tests refactor #3774

multi_tenancy/tests/test_signup.py
Ignores User.uuid field added by PostHog/posthog#3855.
=> Ignore User.uuid in tests

.github/workflows/ci-backend.yml, bin/docker-server-newrelic, bin/pull_main, newrelic.ini, requirements.txt
This PR is part of https://github.com/PostHog/posthog/pull/4005 to introduce NewRelic for our cloud deployment. Please view the referenced PR for more details.
=> Add NewRelic to posthog-cloud

prod.web.Dockerfile
Adds the same commands from `pull_main` to `prod.web.Dockerfile` to run NewRelic﻿
=> Add NewRelic config to production Docker

multi_tenancy/stripe.py, multi_tenancy/tests/test_tasks.py
Fixes https://sentry.io/organizations/posthog/issues/2372018478/?referrer=slack
=> update api call

.github/workflows/ci-backend.yml
* fix saml tests?
Making the same change that was made on https://github.com/PostHog/posthog/pull/7506/commits
* update the other place we do this as well
=> Merge master into cloudfront url update branch
